### ISSUE TITLE
Start button

### ISSUE THREAD

**Issue by dunajski** [Swiatlon/Rock-Paper-Scissors-game#3]
Moim zdaniem fajniej byloby jesli klikanie na poszczegolne ikony od razu zmienialoby wynik, natomiast znak start zastapilbym reset, zeby od nowa naliczac punkty, ale co ja tam wiem! 😹

**Comment by Swiatlon** [comment]
Powiem ci tak nie przerabiałem kodu ale przemyślałem co powiedziałeś i tak jak jest teraz bardziej mi się podoba :D

**Comment by dunajski** [comment]
To zamknij issue następnym razem :-)
